artifact_root: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  source_url: "https://github.com/HimmatMagar/datae/raw/refs/heads/main/australia_visa_applications.zip"
  ziped_data_path: artifact/data_ingestion/data.zip
  unziped_file: artifact/data_ingestion

data_validation:
  root_dir: artifact/data_validation
  file_path: artifact/data_ingestion/australia_visa_applications.csv
  status_file: artifact/data_validation/status.txt

data_transformation:
  root_dir: artifact/data_transformation
  file_path: artifact/data_ingestion/australia_visa_applications.csv

model_building:
  root_dir: artifact/model_building
  x_train_file: artifact/data_transformation/x_train.pkl
  y_train_file: artifact/data_transformation/y_train.pkl
  model: model.pkl

model_evaluation:
  root_dir: artifact/model_evaluation
  x_val_file: artifact/data_transformation/x_val.pkl
  y_val_file: artifact/data_transformation/y_val.pkl
  model: artifact/model_building/model.pkl
  metric_file: artifact/model_evaluation/mertic.json
